trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  GAR_URL: "us-central1-docker.pkg.dev/e00049-development-project/mountain-peak-view/single-page-app"

steps:

# Install Docker
- task: DockerInstaller@0
  displayName: "Install Docker"

# Login to GAR
- task: Docker@2
  displayName: "Login to Google Artifact Registry"
  inputs:
    command: login
    containerRegistry: GAR_Connection_1

# Build Image
- task: Docker@2
  displayName: "Build Docker Image"
  inputs:
    command: build
    repository: $(GAR_URL)
    dockerfile: '**/Dockerfile'
    containerRegistry: GAR_Connection_1
    tags: |
      v$(Build.BuildId)
      latest

# Push Image
- task: Docker@2
  displayName: "Push Docker Image"
  inputs:
    command: push
    repository: $(GAR_URL)
    containerRegistry: GAR_Connection_1
    tags: |
      v$(Build.BuildId)
      latest

# Export Image URI
- script: |
    echo "##vso[task.setvariable variable=IMAGE_URI]$(GAR_URL):v$(Build.BuildId)"
  displayName: "Export IMAGE_URI Variable"

