trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

# Use the Google Cloud SDK image with Docker included
container:
  image: google/cloud-sdk:slim-with-docker

# Link your variable group for GCP credentials
variables:
- group: mountain-peak-view
- name: PROJECT_ID
  value: e00049-development-project
- name: REGION
  value: us-central1
- name: CLUSTER_NAME
  value: mountain-peak-view
- name: IMAGE_REPO
  value: e00049-development-project/mountain-peak-view/single-page-app

steps:

# Checkout the code
- checkout: self
  displayName: "Checkout Source Code"

# Authenticate to GCP & GKE
- script: |
    echo "$(GCP_SA_KEY)" | base64 -d > key.json
    gcloud auth activate-service-account --key-file=key.json
    gcloud config set project $(PROJECT_ID)
    gcloud container clusters get-credentials $(CLUSTER_NAME) --region $(REGION)
    kubectl get nodes
  displayName: "Authenticate to GKE"

# Login to Google Artifact Registry
- script: |
    gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
  displayName: "Login to GAR"

# Build Docker Image with a Dynamic Tag
- script: |
    IMAGE_URI="us-central1-docker.pkg.dev/$(IMAGE_REPO):$(Build.BuildNumber)"
    docker build -t $IMAGE_URI .
    docker tag $IMAGE_URI us-central1-docker.pkg.dev/$(IMAGE_REPO):latest
    echo "##vso[task.setvariable variable=IMAGE_URI]$IMAGE_URI"
  displayName: "Build Docker Image"

# Push the Docker Image to GAR
- script: |
    docker push us-central1-docker.pkg.dev/$(IMAGE_REPO):$(Build.BuildNumber)
    docker push us-central1-docker.pkg.dev/$(IMAGE_REPO):latest
  displayName: "Push Docker Image to GAR"

# Deploy to GKE using the updated image
- script: |
    echo "Deploying Image: $(IMAGE_URI)"
    sed -i "s|IMAGE_PLACEHOLDER|$(IMAGE_URI)|g" deployment/deployment.yaml
    kubectl apply -f deployment/deployment.yaml
    kubectl apply -f deployment/service.yaml
    kubectl rollout status deployment/single-page-app --timeout=180s
  displayName: "Deploy to GKE"

