trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

# ✅ Run all steps inside Google Cloud SDK container
container:
  image: google/cloud-sdk:latest

variables:
  PROJECT_ID: "e00049-development-project"
  REGION: "us-central1"
  CLUSTER_NAME: "mountain-peak-view"
  IMAGE_REPO: "e00049-development-project/mountain-peak-view/single-page-app"

steps:

# ✅ 1️⃣ Checkout Source
- checkout: self
  displayName: "Checkout Source Code"

# ✅ 2️⃣ Authenticate to GCP & GKE
- script: |
    echo "$(GCP_SA_KEY)" | base64 -d > key.json

    echo "✅ Key file created:"
    ls -l key.json

    gcloud auth activate-service-account --key-file=key.json
    gcloud config set project $(PROJECT_ID)
    gcloud container clusters get-credentials $(CLUSTER_NAME) --region $(REGION)

    kubectl get nodes
  displayName: "Authenticate to GKE"
  env:
    GCP_SA_KEY: $(GCP_SA_KEY)


# ✅ 3️⃣ Login to Google Artifact Registry
- script: |
    gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
  displayName: "Login to GAR"

# ✅ 4️⃣ Build Docker Image with Dynamic Build Name
- script: |
    IMAGE_URI="us-central1-docker.pkg.dev/$(IMAGE_REPO):$(Build.BuildNumber)"

    docker build -t $IMAGE_URI .
    docker tag $IMAGE_URI us-central1-docker.pkg.dev/$(IMAGE_REPO):latest

    echo "##vso[task.setvariable variable=IMAGE_URI]$IMAGE_URI"
    echo "Built Image: $IMAGE_URI"
  displayName: "Build Docker Image"

# ✅ 5️⃣ Push Image to GAR
- script: |
    docker push us-central1-docker.pkg.dev/$(IMAGE_REPO):$(Build.BuildNumber)
    docker push us-central1-docker.pkg.dev/$(IMAGE_REPO):latest
  displayName: "Push Docker Image to GAR"

# ✅ 6️⃣ Deploy to GKE using GitHub Deployment YAML
- script: |
    echo "Deploying Image: $(IMAGE_URI)"

    sed -i "s|IMAGE_PLACEHOLDER|$(IMAGE_URI)|g" deployment/deployment.yaml

    cat deployment/deployment.yaml

    kubectl apply -f deployment/deployment.yaml
    kubectl apply -f deployment/service.yaml

    kubectl rollout status deployment/single-page-app --timeout=180s

    echo "✅ Deployment Completed Successfully"
  displayName: "Deploy to GKE"
