trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: mountain-peak-view
- name: PROJECT_ID
  value: e00049-development-project
- name: REGION
  value: us-central1
- name: CLUSTER_NAME
  value: mountain-peak-view
- name: IMAGE_REPO
  value: e00049-development-project/mountain-peak-view/single-page-app

steps:

# Download the secure file (service account key)
- task: DownloadSecureFile@1
  name: 'downloadKey'
  inputs:
    secureFile: 'mountain-peak-view.json'

# Install Docker from Docker’s official repository
- script: |
    sudo apt-get update
    sudo apt-get install -y ca-certificates curl gnupg
    sudo install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    echo \
      "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io
  displayName: 'Install Docker'

# Install Google Cloud SDK
- script: |
    echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
    sudo apt-get update && sudo apt-get install -y google-cloud-sdk
  displayName: 'Install Google Cloud SDK'

# Authenticate to GCP & GKE using the secure file
- script: |
    gcloud auth activate-service-account --key-file=$(downloadKey.secureFilePath)
    gcloud config set project $(PROJECT_ID)
    gcloud container clusters get-credentials $(CLUSTER_NAME) --region $(REGION)
    kubectl get nodes
  displayName: "Authenticate to GKE"

# Login to Google Artifact Registry
- script: |
    gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
  displayName: "Login to GAR"

# Build Docker Image with a Dynamic Tag
- script: |
    IMAGE_URI="us-central1-docker.pkg.dev/$(IMAGE_REPO):$(Build.BuildNumber)"
    docker build -t $IMAGE_URI .
    docker tag $IMAGE_URI us-central1-docker.pkg.dev/$(IMAGE_REPO):latest
    echo "##vso[task.setvariable variable=IMAGE_URI]$IMAGE_URI"
  displayName: "Build Docker Image"

# Push the Docker Image to GAR
- script: |
    docker push us-central1-docker.pkg.dev/$(IMAGE_REPO):$(Build.BuildNumber)
    docker push us-central1-docker.pkg.dev/$(IMAGE_REPO):latest
  displayName: "Push Docker Image to GAR"

# Deploy to GKE using the updated image
- script: |
    echo "Deploying Image: $(IMAGE_URI)"
    sed -i "s|IMAGE_PLACEHOLDER|$(IMAGE_URI)|g" deployment/deployment.yaml
    kubectl apply -f deployment/deployment.yaml
    kubectl apply -f deployment/service.yaml
    kubectl rollout status deployment/single-page-app --timeout=180s
  displayName: "Deploy to GKE"

