trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  IMAGE_REPO: "e00049-development-project/mountain-peak-view/single-page-app"

steps:
# Install Docker
- task: DockerInstaller@0
  displayName: "Install Docker"

# Login to GAR
- task: Docker@2
  displayName: "Login to Google Artifact Registry"
  inputs:
    command: login
    containerRegistry: GAR_Connection_1

# ✅ Build Image (NO hostname here!)
- task: Docker@2
  displayName: "Build Docker Image"
  inputs:
    command: build
    repository: $(IMAGE_REPO)
    dockerfile: '**/Dockerfile'
    tags: |
      v$(Build.BuildId)
      latest

# ✅ Push Image (NO hostname here!)
- task: Docker@2
  displayName: "Push Docker Image"
  inputs:
    command: push
    repository: $(IMAGE_REPO)
    tags: |
      v$(Build.BuildId)
      latest

# Export Image URI
- script: |
    echo "##vso[task.setvariable variable=IMAGE_URI]us-central1-docker.pkg.dev/$(IMAGE_REPO):v$(Build.BuildId)"
  displayName: "Export IMAGE_URI"

