trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

# Use Google Cloud SDK container
container:
  image: google/cloud-sdk:latest

# Set variables for the pipeline
variables:
- name: PROJECT_ID
  value: e00049-development-project
- name: REGION
  value: us-central1
- name: CLUSTER_NAME
  value: mountain-peak-view
- name: IMAGE_REPO
  value: e00049-development-project/mountain-peak-view/single-page-app

steps:

# Checkout the source code
- checkout: self
  displayName: "Checkout Source Code"

# Download the GCP service account key from Secure Files
- task: DownloadSecureFile@1
  name: gcpkey
  displayName: "Download GCP Service Account Key"
  inputs:
    secureFile: mountain-peak-view.json

# Authenticate to GCP and configure kubectl for GKE
- script: |
    gcloud auth activate-service-account --key-file=$(gcpkey.secureFilePath)
    gcloud config set project $(PROJECT_ID)
    gcloud container clusters get-credentials $(CLUSTER_NAME) --region $(REGION)

    # Verify connection
    kubectl get nodes
  displayName: "Authenticate to GKE"

# Login to Google Artifact Registry
- script: |
    gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
  displayName: "Login to GAR"

# Build Docker Image with dynamic tag
- script: |
    IMAGE_URI="us-central1-docker.pkg.dev/$(IMAGE_REPO):$(Build.BuildNumber)"

    docker build -t $IMAGE_URI .
    docker tag $IMAGE_URI us-central1-docker.pkg.dev/$(IMAGE_REPO):latest

    echo "##vso[task.setvariable variable=IMAGE_URI]$IMAGE_URI"
    echo "Built Image: $IMAGE_URI"
  displayName: "Build Docker Image"

# Push the Docker image to GAR
- script: |
    docker push us-central1-docker.pkg.dev/$(IMAGE_REPO):$(Build.BuildNumber)
    docker push us-central1-docker.pkg.dev/$(IMAGE_REPO):latest
  displayName: "Push Docker Image to GAR"

# Deploy to GKE using the deployment YAML
- script: |
    echo "Deploying Image: $(IMAGE_URI)"

    sed -i "s|IMAGE_PLACEHOLDER|$(IMAGE_URI)|g" deployment/deployment.yaml

    kubectl apply -f deployment/deployment.yaml
    kubectl apply -f deployment/service.yaml

    echo "✅ Deployment Completed Successfully"
  displayName: "Deploy to GKE"
